#!/usr/bin/env node
const https = require('https');
const querystring = require('querystring');
const recaptcha = process.argv[2];

const postData = querystring.stringify({
  secret: '6LdHUW8UAAAAAKqGpK7U06jCNWyort9VA4XxG9Ol',
  response: recaptcha
});

const options = {
  hostname: 'www.google.com',
  port: 443,
  path: '/recaptcha/api/siteverify',
  method: 'POST',
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Content-Length': postData.length
  }
};

const req = https.request(options, (res) => {
  res.on('data', (data) => {
    process.stdout.write(data + '\n');
  });
});

req.on('error', (e) => {
  console.error(e);
});

req.write(postData);
req.end();
